In [1]:
import numpy as np

# part 1
Все задания рекомендуется делать вручную, проверяя полученные результаты через NumPy.

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    


m x n, m = строка, n = столбец<br>
а)строка не равна столбцу<br>
б)2х3<br>
в)8х8<br>
г)4х4<br>

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


In [2]:
print('сумма матриц:')
c11 = 1+4
c12 = -2-1
c21 = 3+0
c22 = 0+5
print(f'{c11} {c12}\n{c21}  {c22}\n')
print('произведение матриц A и B:')
c11 = (1 * 4) + (-2 * 0)
c12 = (1 * -1) + (-2 * 5)
c21 = (3 * 4) + (0 * 0)
c22 = (3 * -1) + (0 * 5)

print(f'0{c11} {c12}\n{c21} {c22}\n')
print('проверка numpy:')
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(A+B)
print()
print(A @ B)
# matrixmult(A,B)

сумма матриц:
5 -3
3  5

произведение матриц A и B:
04 -11
12 -3

проверка numpy:
[[ 5 -3]
 [ 3  5]]

[[  4 -11]
 [ 12  -3]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$


In [3]:
r11 = 3 * 1 - 2 * 0 + 4 * 2
r12 = 3 * 7 - 2 * 5 + 4 * -4
r21 = 3 * 3 - 2 * 2 + 4 * 1
r22 = 3 * -6 - 2 * -1 + 4 * 1
print(f'{r11} {r12}\n{r21} {r22}\n')
print('проверка numpy:')
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
3 * A - 2 * B + 4 * C

11 -5
9 -12

проверка numpy:


array([[ 11,  -5],
       [  9, -12]])

    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.



$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$.

In [4]:
# aat = 3x3
aat11 = 4 * 4 + 1 * 1
aat12 = 5 * 4 - 2 * 1
aat13 = 2 * 4 + 3 * 1
aat21 = 4 * 5 + 1 * -2
aat22 = 5 * 5 - 2 * -2
aat23 = 2 * 5 + 3 * -2
aat31 = 4 * 2 + 1 * 3
aat32 = 5 * 2 - 2 * 3
aat33 = 2 * 2 + 3 * 3
print(f'{aat11} {aat12} {aat13}\n{aat21} {aat22} {aat23}\n{aat31} {aat32} {aat33}\n')
# ata = 2x2
ata11 = 4 * 4 + 5 * 5 + 2 * 2
ata12 = 4 * 1 + 5 * -2 + 2 * 3
ata21 = 1 * 4 + -2 * 5 + 3 * 2
ata22 = 1 * 1 + -2 * -2 + 3 * 3
print(f'{ata11} {ata12}\n{ata21} {ata22}\n')
print('проверка numpy:')
A = np.array([[4,1],[5,-2],[2,3]])
AT = np.array([[4,5,2],[1,-2,3]])
# AT = A.T
AAT = A @ AT
ATA = AT @ A
print('AAT:\n',AAT,'\n\nATA:\n', ATA)
# print()
# print(matrixmult(A,AT))
# print()
# print(matrixmult(AT,A))

17 18 11
18 29 4
11 4 13

45 0
0 14

проверка numpy:
AAT:
 [[17 18 11]
 [18 29  4]
 [11  4 13]] 

ATA:
 [[45  0]
 [ 0 14]]


__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

$$\begin{pmatrix}
a_{1} & a_{2}\\ 
a_{3} & a_{4}
\end{pmatrix} \begin{pmatrix}
b_{1} & b_{2}\\ 
b_{3} & b_{4}
\end{pmatrix}=\begin{pmatrix}
(a_{1}b_{1} + a_{2}b_{3}) & (a_{1}b_{2} + a_{2}b_{4})\\ 
(a_{3}b_{1} + a_{4}b_{3}) & (a_{3}b_{2} + a_{4}b_{4})
\end{pmatrix}.$$

In [5]:
def matrixmult(A, B):
    try:
        temp_a = []
        temp_b = []
        for i in range(len(A)):
            for j in range(len(B[0])):
                s=0
                for k in range(len(B)):
                    s=s+(A[i][k]*B[k][j])
                temp_a.append(s)
            temp_b.append(temp_a)
            temp_a=[]
        return temp_b
    except Exception as e:
        print('число столбцов матрицы A должно быть равно числу строк матрицы B')
        return

In [6]:
A = [[0,1],[1,0]]
B = [[1,0],[1,1]]
matrixmult(A,B)

[[1, 1], [1, 0]]

In [7]:

a = np.array(A)
b = np.array(B)
a @ b

array([[1, 1],
       [1, 0]])

# part 2
Все задания рекомендуется выполнять вручную, проверяя полученные результаты с использованием NumPy.

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$



a) sinx * sinx - (-cosx * cosx) = 1<br>
б) 4 * 5 * 9 = 180<br>
в) 1 * 18 * 26 = 468<br>
1) из строки 2 вычтем строку 1 умноженную на 4<br>
2) из строки 3 вычтем строку 1 умноженную на 7<br>
3) из строки 3 вычтем строку 2 умноженную на 2<br>
4) из строки 3 вычтем строку 2 деленую на 3<br>

$$\begin{vmatrix}
1 & 2 & 3\\ 
0 & 18 & -6\\ 
0 & 0 & 26
\end{vmatrix}.$$

In [8]:
B = np.array([[4,2,3],[0,5,1],[0,0,9]])
C = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.linalg.det(B), np.linalg.det(C))

180.0 6.66133814775094e-16



__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.


a) 4, $det(AB)=detA\cdot detB.$, что должно работать и в случае A @ A<br>
б) 4, $detA^{T}=detA.$<br>
в) 8, <br>

   
__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.



In [9]:
A = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(A)
print('определитель матрицы равен нулю, значит матрица вырожденная')

определитель матрицы равен нулю, значит матрица вырожденная


__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

a)
1) умножить первую строку на -1, прибавить к ней вторую <br>
2) умножить 2ю строку на -2, прибавить к ней третью<br>
3) получится
$\begin{pmatrix}
0 & -1 & -2\\ 
0 & 1 & 2\\ 
2 & 3 & 4
\end{pmatrix}$<br>
4) первая и вторая пропорциональны, можно отбросить любую<br>
5) ранг матрицы 2<br><br>
б)
1) третья строка это сумма 1 и второй строки, значит можно отбросить<br>
2) больше ничего не вижу, ранг 3<br>


In [10]:
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
b = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(a), np.linalg.matrix_rank(b)


(2, 3)