1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$




In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [3]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3,-4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [4]:
U, s, W = np.linalg.svd(A)
V = W.T
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [5]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [6]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [7]:
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1. -0. -0.]
 [ 0. -0. -0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [8]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [9]:
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [15]:
# a) если известны сингулярные числа матрицы А, то евклидова норма это максимальное значение среди диагонали матрцы D
# а максимальное значение всегда в одной и той же точке:
print(f'{s[0]} or {D[0,0]}, что есть одно и то же')

8.824868854820448 or 8.824868854820448, что есть одно и то же


In [18]:
# б) норма Фробениуса, получается, это корень из суммы квадратов сингулярных чисел, что по диагонали матрицы D
frob = 0
for el in s:
    frob+=el**2
np.sqrt(frob)

11.045361017187265

In [21]:
s**2, sum(s**2), np.sqrt(sum(s**2))

(array([77.88, 37.71,  6.41]), 122.00000000000007, 11.045361017187265)

In [23]:
# норма Фробениуса, если использовать изначальную матрицу
A**2, sum(sum(A**2)), np.sqrt(sum(sum(A**2)))

(array([[ 1,  4,  0],
        [ 0,  0, 25],
        [ 9, 16,  4],
        [ 1, 36, 25],
        [ 0,  1,  0]], dtype=int32),
 122,
 11.045361017187261)