In [1]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)





__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



In [4]:
a = np.array([[-1,-6],[2,6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.





In [5]:
a = np.array([[-1,0],[0,-1]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


не понимаю какой я вывод должен делать из результатов np.linalg.eig по этой матрице, но логика простая <br>
поворот на 180 градусов это вернуться в изначальную позицию <br>
тоесть сделать целый круг и ничего не изменится, какой бы вектор туда не приложили

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

In [6]:
a = np.array([[1,1],[-1,3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


помножив матрицу на вектор получается что<br>
1+1 = alpha <br>
-1+3 = alpha <br>
alpha = 2 <br>
альфа одинаковый, значит является собственным вектором

**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [7]:
a = np.array([[0,3,0],[3,0,0],[0,0,3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


(0 * 3) + (3 * -3) + (0 * -4) = 3 * a <br>
3 * -3 + 0 + 0 = -3 * a <br>
0 + 0 + 3* -4 = -4 * a <br>

9 = 3a <br>
-9 = -3a <br>
-12 = -4a <br>
Значения a совпадают, значит вектор является собственным